// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEGget-wTjenABBO0WXyldb9LKHBg7JEc',
    appId: '1:696004120917:web:3966b663b41f7ae49b9fdc',
    messagingSenderId: '696004120917',
    projectId: 'attendance-system-d4f1b',
    authDomain: 'attendance-system-d4f1b.firebaseapp.com',
    storageBucket: 'attendance-system-d4f1b.firebasestorage.app',
    measurementId: 'G-GNCF943YXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn_MLxNKbNqrKRlv-V76YJmexqXtbdP_w',
    appId: '1:696004120917:android:96471487a31d4d029b9fdc',
    messagingSenderId: '696004120917',
    projectId: 'attendance-system-d4f1b',
    storageBucket: 'attendance-system-d4f1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAH5gI7ow3aKYGu5Sjho6cVKZGjHjDdQk',
    appId: '1:696004120917:ios:872d5d58a1d75d8f9b9fdc',
    messagingSenderId: '696004120917',
    projectId: 'attendance-system-d4f1b',
    storageBucket: 'attendance-system-d4f1b.firebasestorage.app',
    iosBundleId: 'com.example.attendanceSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAH5gI7ow3aKYGu5Sjho6cVKZGjHjDdQk',
    appId: '1:696004120917:ios:872d5d58a1d75d8f9b9fdc',
    messagingSenderId: '696004120917',
    projectId: 'attendance-system-d4f1b',
    storageBucket: 'attendance-system-d4f1b.firebasestorage.app',
    iosBundleId: 'com.example.attendanceSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEGget-wTjenABBO0WXyldb9LKHBg7JEc',
    appId: '1:696004120917:web:1f6a9be868cfdfe79b9fdc',
    messagingSenderId: '696004120917',
    projectId: 'attendance-system-d4f1b',
    authDomain: 'attendance-system-d4f1b.firebaseapp.com',
    storageBucket: 'attendance-system-d4f1b.firebasestorage.app',
    measurementId: 'G-E5RD6GG67M',
  );

}